Repository dannysanchez559/poke-app, pull requests merged in 2021-08, with the labels that each got.

#75 Click Card to open modal.
  public/pokeapi-js-wrapper-sw.js
  src/components/Modal.js
  src/components/PokeCard.js
  src/components/PokemonDetails.js
  src/components/TabBar.js
  src/components/TabPanel.js
Labels: enhancement

#76 display modal evolution tab content
  src/components/EvolutionTab.js
  src/components/PokeCard.js
  src/img/evolution-arrow.png
  src/styles/components/_modal.scss
Labels: enhancement

#77 Modal Styling
  src/components/Modal.js
  src/components/PokeList.js
  src/components/TabBar.js
  src/styles/_typography.scss
  src/styles/components/_card.scss
  src/styles/components/_modal.scss
Labels: enhancement

#79 Base Stats Tab Styling
  src/components/BaseStats.js
  src/styles/components/_modal.scss
Labels: enhancement

#81 PokeApi JS Wrapper configuration and fetch refactoring
  package-lock.json
  package.json
  public/index.html
  src/components/Nav.js
  src/components/PokeApp.js
  src/components/PokeCard.js
  src/components/PokemonDetails.js
  src/util/fetchPokemonData.js
Labels: bug, enhancement

#83 Modal About Tab Styling
  src/components/EvolutionTab.js
  src/components/PokemonDetails.js
  src/styles/_typography.scss
  src/styles/components/_modal.scss
Labels: enhancement

#89 Moves tab styling
  src/components/BaseStats.js
  src/components/Moves.js
  src/components/PokeCard.js
  src/components/PokeList.js
  src/img/typeIcons/bug.png
  src/img/typeIcons/dark.png
  src/img/typeIcons/dragon.png
  src/img/typeIcons/electric.png
  src/img/typeIcons/fairy.png
  src/img/typeIcons/fighting.png
  src/img/typeIcons/fire.png
  src/img/typeIcons/flying.png
  src/img/typeIcons/ghost.png
  src/img/typeIcons/grass.png
  src/img/typeIcons/ground.png
  src/img/typeIcons/ice.png
  src/img/typeIcons/images.js
  src/img/typeIcons/normal.png
  src/img/typeIcons/poison.png
  src/img/typeIcons/psychic.png
  src/img/typeIcons/rock.png
  src/img/typeIcons/steel.png
  src/img/typeIcons/water.png
  src/styles/_typography.scss
  src/styles/components/_modal.scss
  src/util/fetchPokemonData.js
Labels: enhancement

#86 Refactor PokeApp & components, move fetching to child components, lazyload.
  package-lock.json
  package.json
  src/components/EvolutionTab.js
  src/components/Loader.js
  src/components/Modal.js
  src/components/Moves.js
  src/components/PokeApp.js
  src/components/PokeCard.js
  src/components/PokeList.js
  src/components/PokemonDetails.js
  src/components/Searched.js
  src/components/TabBar.js
  src/components/TabPanel.js
  src/styles/components/_loader.scss
  src/styles/components/_modal.scss
  src/styles/main.scss
  src/util/fetchPokemonData.js
Labels: enhancement

#93 Infinite scroll
  src/components/PokeApp.js
  src/components/PokeList.js
  src/util/fetchPokemonData.js
Labels: enhancement

#97 Add Spinner
  public/ballSpin.png
  src/components/BaseStats.js
  src/components/Loader.js
  src/components/Moves.js
  src/components/PokeApp.js
  src/components/PokeList.js
  src/components/PokemonDetails.js
  src/components/Searchbar.js
  src/components/Searched.js
  src/components/Spinner.js
  src/styles/components/_ball_spin.scss
  src/styles/components/_loader.scss
  src/styles/main.scss
Labels: enhancement

#98 Ds 78 finish desktop styling
  package-lock.json
  src/components/EvolutionTab.js
  src/components/Modal.js
  src/components/Moves.js
  src/components/PokeApp.js
  src/components/PokeCard.js
  src/components/TabBar.js
  src/img/evolution-arrow 2.png
  src/img/wpkb 2.svg
  src/styles/_typography.scss
  src/styles/components/_card.scss
  src/styles/components/_filterbar.scss
  src/styles/components/_header.scss
  src/styles/components/_modal.scss
  src/styles/main.scss
Labels: enhancement

#101 Modal and Card Animation
  package-lock.json
  package.json
  src/components/Header.js
  src/components/Moves.js
  src/components/PokeCard.js
  src/styles/components/_card.scss
  src/styles/components/_filterbar.scss
  src/styles/components/_header.scss
  src/styles/components/_modal.scss
  src/styles/main.scss
Labels: enhancement

#103 Ds 102 change project logo
  public/allPokemonLogo.png
  public/allPokemonLogo.svg
  public/favicon.ico
  public/gamesLogo.png
  public/gamesLogo.svg
  public/logo.svg
  public/logo192.png
  public/logo512.png
  public/pocketDexLogo.svg
  public/searchBarLogo.png
  public/searchBarLogo.svg
  public/toggle.png
  public/toggle.svg
  public/topPicksLogo.png
  public/topPicksLogo.svg
  src/components/Filter.js
  src/components/Header.js
  src/logo.svg
  src/styles/components/_header.scss
Labels: enhancement

#116 Ds 106 modal responsive design
  public/favicon 2.ico
  src/styles/_typography.scss
  src/styles/components/_modal.scss
Labels: enhancement

#119 Modal and Spinner Positioning
  src/components/BaseStats.js
  src/components/EvolutionTab.js
  src/components/Moves.js
  src/components/PokeApp.js
  src/components/PokeList.js
  src/components/PokemonDetails.js
  src/components/Searched.js
  src/components/Spinner.js
  src/styles/components/_ball_spin.scss
  src/styles/components/_modal.scss
  src/styles/main.scss
Labels: enhancement

#120 Naming refactor, added some comments then fixed merge conflicts
  src/components/FilterBar.js
  src/components/Header.js
  src/components/PokeApp.js
  src/components/PokeList.js
  src/components/Searched.js
  src/components/TabBar.js
  src/components/TabPanel.js
  src/util/FilterTypes.js
  src/util/SortTypes.js
  src/util/allTypes.js
  src/util/getTypeColor.js
Labels: enhancement

#121 Add error handling for modal
  src/components/EvolutionTab.js
  src/components/PokeCard.js
Labels: enhancement

#123 fix(index.html): comment out a line causing error in console
  public/index.html
Labels: enhancement

#125 Move searchedCard styling from main.scss to _card.scss, center card
  src/styles/components/_card.scss
  src/styles/main.scss
Labels: enhancement

#127 Display names of evolutionary stages in Evolution Tab
  src/components/EvolutionTab.js
  src/styles/_typography.scss
  src/styles/components/_modal.scss
Labels: enhancement

#129 Update version in package.json and README.
  README.md
  package.json
Labels: documentation

#136 Filter fix and search edgecase
  .firebase/hosting.YnVpbGQ.cache
  src/components/PokeApp.js
  src/components/PokeList.js
Labels: bug

#140 Add toLowerCase() to search input
  .firebase/hosting.YnVpbGQ.cache
  src/components/PokeApp.js
Labels: enhancement

#142 Remove links in Header and modified scss
  src/components/Header.js
  src/styles/components/_header.scss
Labels: enhancement

#146 Ds 139 pokeball spinner positioning
  src/components/BaseStats.js
  src/components/EvolutionTab.js
  src/components/Moves.js
  src/components/PokeCard.js
  src/components/PokemonDetails.js
  src/components/Spinner.js
  src/styles/components/_ball_spin.scss
Labels: bug

#152 Nav Link Alignment
  src/styles/_typography.scss
  src/styles/components/_header.scss
Labels: bug

#154 fix(modal): center evolution sprites inside modal for all cases
  src/components/EvolutionTab.js
  src/styles/components/_modal.scss
Labels: bug

#159 Ds 92 remove newline from about description
  src/components/PokemonDetails.js
Labels: bug

#165 Filter fix
  .firebase/hosting.YnVpbGQ.cache
  src/components/PokeList.js
Labels: enhancement

#166 Merge Fixes to Main
  .firebase/hosting.YnVpbGQ.cache
  public/allPokemonLogo.svg
  public/allPokemons.png
  src/components/BaseStats.js
  src/components/EvolutionTab.js
  src/components/Header.js
  src/components/Moves.js
  src/components/PokeApp.js
  src/components/PokeCard.js
  src/components/PokeList.js
  src/components/PokemonDetails.js
  src/components/Searched.js
  src/components/Spinner.js
  src/styles/_typography.scss
  src/styles/components/_ball_spin.scss
  src/styles/components/_header.scss
  src/styles/components/_modal.scss
  src/util/fetchPokemonData.js
Labels: enhancement
